In [1]:
# import modules
import numpy as np
import sys 

## The Basics

In [12]:
 # Create array with list
a = np.array([1,2,3], dtype=np.int32) # can specify dtype
b = np.array([[1,2,3,5],[4,5,6,7]]) # default is np.int64

In [25]:
# Create array with 0s
c = np.zeros([3,4]) # note default is float
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
# Create array with 1s
d = np.ones([3,4])
d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [148]:
# Create array with random values
f = np.random.default_rng(0).random(5)
f

array([0.63696169, 0.26978671, 0.04097352, 0.01652764, 0.81327024])

In [150]:
# Random integer numbers within a range with size
f2 = np.random.default_rng(0).integers(8, size=(2,5))
f2

array([[6, 5, 4, 2, 2],
       [0, 0, 0, 1, 6]])

In [31]:
# Create array with range of elements [exclusive]
e = np.arange(6)
e

array([0, 1, 2, 3, 4, 5])

In [33]:
# Create empty array. Initial content is random and depends on the state of the memory.
f = np.empty(6)
f

array([4.64358516e-310, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000])

In [34]:
# Create array with intervals.
g = np.arange(2,18, 2) # From 2 to 18 step 2
g

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [38]:
# Create linearly spaced array
h = np.linspace(2,25, num=10) #  can specify dtype. default is float
h

array([ 2.        ,  4.55555556,  7.11111111,  9.66666667, 12.22222222,
       14.77777778, 17.33333333, 19.88888889, 22.44444444, 25.        ])

In [13]:
# Get dimentions
print(a.ndim)
print(b.ndim)

1
2


In [14]:
# Get type
print(a.dtype)
print(b.dtype) # note default

int32
int64


In [15]:
# Get  item size
print(a.itemsize)
print(b.itemsize)

4
8


In [16]:
# Get byte size
print(a.nbytes)
print(b.nbytes)

12
64


In [58]:
# Get size - number of elements in array
a.size

3

## Access, Update, Slicing

In [73]:
# Retrieve using single index
a[2]

3

In [76]:
# Retrieve range of elements
a[:2]

array([1, 2], dtype=int32)

In [77]:
# Retrieve last element
a[-1]

3

In [85]:
# Retrieve from last to first = reverses array
a[::-1]

array([3, 2, 1], dtype=int32)

In [19]:
# Access specific item [row,col]
print(b[0,3]) #retrieve fourth element from first row
print(b[1,0]) # first element from second row

5
4


In [86]:
# Elements < 3
a[a < 3]

array([1, 2], dtype=int32)

In [87]:
# Elements > 2
a[a > 2]

array([3], dtype=int32)

In [88]:
# ELements >= 3
a[a >= 2]

array([2, 3], dtype=int32)

In [102]:
# Satisfy multiple conditions
print(a[(a > 1) & (a <= 3)]) # and
print(a[(a > 1) | (a <= 3)]) # or
print(a[a % 2 ==0]) # mod

[1 2 3]
[2 3]
[1 2 3]
[2]


In [97]:
# Return booleans 
print((a<2) & (a > -1))

[ True False False]


In [105]:
# Use nonzero to print indces & elements
print(a)
print(np.nonzero(a > 1)) # print indices greater than 1
print(np.nonzero(a[a > 1])) # print elements greater than 1

[1 2 3]
(array([1, 2]),)
(array([0, 1]),)


## Sorting, Adding, and Removing

In [47]:
new_arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr = np.array([[2,5,6,8,3],[7,3,5,1,4]])

In [48]:
# Sort
np.sort(new_arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [51]:
# Argsort sorts along a specific axis
np.argsort(arr, axis=0)

array([[0, 1, 1, 1, 0],
       [1, 0, 0, 0, 1]])

In [52]:
# Add arrays
first = np.array([1,2,3,4])
second = np.array([5,6,7,8])

first + second

array([ 6,  8, 10, 12])

In [54]:
# Concatenate arrays
np.concatenate([first, second])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [56]:
# Remove
# It's easier to use indexing to select elements you want to keep
new_ar = first[0:3]
new_ar

array([1, 2, 3])

## Reshape Array

In [60]:
r = np.arange(6)
r

array([0, 1, 2, 3, 4, 5])

In [61]:
# np.reshape
m = r.reshape(3,2) # new shape must be compatible with original
m

array([[0, 1],
       [2, 3],
       [4, 5]])

## Add new Axis to Array

In [67]:
# np.newaxis increases array dimension by 1. 1D > 2D / 2D > 3D
print(r.shape)
r2 = r[np.newaxis, :] # row vector
print(r2)
print(r2.shape)

(6,)
[[0 1 2 3 4 5]]
(1, 6)


In [68]:
r3 = r[:, np.newaxis] # col vector
print(r3)
print(r3.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
(6, 1)


In [70]:
# Add new axis at specified position
r4 = np.array([1, 2, 3, 4, 5, 6])
r4.shape

(6,)

In [71]:
# Add axis at index 1
r5 = np.expand_dims(r4, axis=1)
r5.shape

(6, 1)

In [72]:
# Add axis at index 0
r6 = np.expand_dims(r4, axis=0)
r6.shape

(1, 6)

## Create Array from Existing Data

In [107]:
x = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [109]:
# Using slicing
n1 = x[:6]
n1

array([1, 2, 3, 4, 5, 6])

In [112]:
# Stack arrays
q1 = np.array([[1,1], [2,2]])
q2 = np.array([[3,3], [4,4]])

In [114]:
# vstack
v1 = np.vstack((q1, q2))
v1

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [115]:
# hstack
v2 = np.hstack((q1,q2))
v2

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [119]:
# Split array using hsplit
np.hsplit(x, 2)

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]

In [122]:
np.hsplit(v2, 2)

[array([[1, 1],
        [2, 2]]),
 array([[3, 3],
        [4, 4]])]

In [127]:
# Make a copy of array
v2_cpy = v2.copy    
print(v2_cpy)
np.copy(v2) # returns the copied array

<built-in method copy of numpy.ndarray object at 0x7f34fe4f3330>


array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

## Basic Operations

In [129]:
# Add arrays
d1, d2 = np.hsplit(x, 2) # create 2 arrays using hsplit
d1 + d2

array([ 7,  9, 11, 13, 15])

In [131]:
# Subtract 
d2 - d1

array([5, 5, 5, 5, 5])

In [132]:
# Multiply
d1 * d2

array([ 6, 14, 24, 36, 50])

In [133]:
# Divide
d2 / d1

array([6.        , 3.5       , 2.66666667, 2.25      , 2.        ])

In [135]:
# Sum of elements in array
x.sum()

55

In [139]:
# Sum rows
print(v2.sum(axis=0))
print(v2.sum(axis=1))

[3 3 7 7]
[ 8 12]


In [143]:
# Aggregation Operations. can aggregate across rows/cols using axis
print(x.max())
print(x.min()) 

10
1


## Broadcasting
Broadcasting is a mechanism that allows NumPy to perform operations on arrays of different shapes. 

In [141]:
# example
a * 2

array([2, 4, 6], dtype=int32)

## Unique Items and Counts

In [159]:
x = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
x_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [154]:
# Unique values
np.unique(x)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [155]:
# Get indices of unique values
np.unique(x, return_index=True)

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14]))

In [156]:
# Get counts of unique values
np.unique(x, return_counts=True)

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([3, 2, 2, 2, 1, 1, 1, 1, 1, 1]))

In [157]:
# Get inverse of unique values
np.unique(x, return_inverse=True)

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([0, 0, 1, 2, 3, 4, 5, 6, 1, 2, 0, 3, 7, 8, 9]))

In [160]:
# For matrix
np.unique(x_2d)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [161]:
# Get row or col based unique values
np.unique(x_2d, axis=1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [162]:
np.unique(x_2d, axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [164]:
# Get unique rows, indices, and counts
rows, indices, counts = np.unique(x_2d, axis=0, return_counts=True, return_index=True)
print('Row ==> ', rows)
print('Indices ==> ', indices)
print('Counts ==> ',counts)

Row ==>  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Indices ==>  [0 1 2]
Counts ==>  [2 1 1]


## Transpose & Reshape

In [170]:
# Reshape
x_sh = x_2d.reshape(2,8)
x_sh

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  1,  2,  3,  4]])

In [176]:
# Transpose using T or transpose
x_T = x_sh.T
print(x_T)
print('=========')
x_t = x_sh.transpose()
print(x_t)

[[ 1  9]
 [ 2 10]
 [ 3 11]
 [ 4 12]
 [ 5  1]
 [ 6  2]
 [ 7  3]
 [ 8  4]]
[[ 1  9]
 [ 2 10]
 [ 3 11]
 [ 4 12]
 [ 5  1]
 [ 6  2]
 [ 7  3]
 [ 8  4]]


## Reverse Array

In [177]:
# Reverse 1D array
np.flip(x)

array([20, 19, 18, 14, 11, 13, 12, 17, 16, 15, 14, 13, 12, 11, 11])

In [178]:
# Reverse 2D
np.flip(x_2d)

array([[ 4,  3,  2,  1],
       [12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [179]:
# Reverse by axis
np.flip(x_2d, axis=1)

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9],
       [ 4,  3,  2,  1]])

In [180]:
np.flip(x_2d, axis=0)

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [183]:
# Reverse only one row
np.flip(x_2d[1])

array([8, 7, 6, 5])

In [184]:
# Reverse on a col
np.flip(x_2d[:,1])

array([ 2, 10,  6,  2])

## Flatten Array

In [186]:
# Flatten - using ravel() makes changes in place
x_2d.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  1,  2,  3,  4])

## Save and Load Numpy Objects

If you want to store a single ndarray object, store it as a .npy file using np.save. 
If you want to store more than one ndarray object in a single file, save it as a .npz file using np.savez.

In [ ]:
# save()
np.save('tutorial.npy', x)

In [ ]:
# savez
np.save('tutorial.npz', x_2d)

In [ ]:
# load
z = np.load('tutorial.npy', x)
y = np.load('tutorial.npz', x_2d)

In [ ]:
# Save as .cvs / txt with np.savetxt
# With savetxt, you can specify headers, footers, comments, and more.
z1 = np.savetxt('tutorial.txt', x)
z2 = np.savetxt('tutorial.csv', x)

In [ ]:
# Load
z3 = np.loadtxt('tutorial.txt', x)
y2 = np.loadtxt('tutorial.csv', x_2d)

## Importing and Exporting CSV

In [ ]:
# Read csv
ar = pd.read_csv('data.csv', header=0).values

# You can specify cols
ar = pd.read_csv('data.csv', usecols=['date_created', 'status']).values